name: Build Android APK on: 
  workflow_dispatch: push:
    branches: [ "main" ] jobs: build: 
    runs-on: ubuntu-latest steps:
      - name: Checkout uses: 
        actions/checkout@v4
      - name: Set up Java 17 uses: 
        actions/setup-java@v4 with:
          distribution: temurin java-version: 
          "17" cache: gradle
      - name: Set up Android SDK uses: 
        android-actions/setup-android@v3
      - name: Accept SDK licenses run: yes | 
        sdkmanager --licenses
      - name: Cache Gradle uses: 
        actions/cache@v4 with:
          path: | ~/.gradle/caches 
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ 
          hashFiles('**/*.gradle*', 
          '**/gradle-wrapper.properties') }} 
          restore-keys: ${{ runner.os 
          }}-gradle-
      # (Opcional) Injetar keystore para 
      # assinar release
      - name: Restore keystore if: ${{ 
        secrets.ANDROID_KEYSTORE_BASE64 != '' 
        }}
        run: | echo 
          "$ANDROID_KEYSTORE_BASE64" | base64 
          -d > android/app/release.keystore
        env: ANDROID_KEYSTORE_BASE64: ${{ 
          secrets.ANDROID_KEYSTORE_BASE64 }}
      - name: Build Release 
        working-directory: android env:
          ORG_GRADLE_PROJECT_ANDROID_KEYSTORE_PATH: 
          ${{ github.workspace 
          }}/android/app/release.keystore
          ORG_GRADLE_PROJECT_ANDROID_KEYSTORE_PASSWORD: 
          ${{ secrets.KEYSTORE_PASSWORD }} 
          ORG_GRADLE_PROJECT_ANDROID_KEY_ALIAS: 
          ${{ secrets.KEY_ALIAS }} 
          ORG_GRADLE_PROJECT_ANDROID_KEY_PASSWORD: 
          ${{ secrets.KEY_PASSWORD }}
        run: | chmod +x gradlew ./gradlew 
          clean :app:assembleRelease
      - name: Upload APK uses: 
        actions/upload-artifact@v4 with:
          name: app-release-apk
          path: android/app/build/outputs/apk/release/*.apk
