name: Build Cordova Android (debug)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Setup Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          # NADA de cache aqui!

      - name: Install deps
        run: |
          npm ci || npm install
          npm i -g cordova@12

      - name: Cordova Android build (debug)
        run: |
          cordova telemetry off || true
          cordova platform rm android || true
          cordova platform add android@11
          cordova build android --debug --no-interactive

      - name: Upload APK (debug)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
