name: Build Cordova Android (debug)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Install Cordova CLI
        run: npm i -g cordova@12

      # SDK + licenças para cordova-android@11 (AGP 7.x / SDK 32)
      - name: Install Android SDK components
        run: |
          sudo mkdir -p "$ANDROID_SDK_ROOT"
          sudo chown -R "$USER":"$USER" "$ANDROID_SDK_ROOT"
          yes | sdkmanager --licenses
          yes | sdkmanager "cmdline-tools;latest" "platform-tools" "platforms;android-32" "build-tools;32.0.0"

      - name: Install project deps
        run: npm ci || npm i

      - name: Add platform & build
        run: |
          cordova platform rm android || true
          cordova platform add android@11
          cordova build android --debug --no-interactive

      - name: Upload APK (debug)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
