name: Build Cordova Android (debug)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Set up Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Install Cordova CLI
        run: npm i -g cordova@12

      # Instala cmdline-tools;latest e SDKs necessários
      - name: Install Android SDK components
        run: |
          sudo mkdir -p "$ANDROID_SDK_ROOT"
          sudo chown -R "$USER":"$USER" "$ANDROID_SDK_ROOT"
          echo y | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --version >/dev/null 2>&1 || true
          yes | sdkmanager "cmdline-tools;latest"
          yes | sdkmanager --licenses
          yes | sdkmanager "platform-tools" "platforms;android-32" "build-tools;32.0.0"

      - name: Install project deps
        run: |
          npm ci || npm i

      - name: Add platform & build (android@11)
        run: |
          cordova platform rm android || true
          cordova platform add android@11
          cordova build android --debug --no-interactive

      - name: Upload APK (debug)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
